### ISSUE TITLE
抓取的圖片全部為馬賽克

### ISSUE THREAD

**Issue by huoqianyu** [CindyLinz/Chrome-BookWalker#1]
尊敬的CindyLinz：
您好，首先感謝您製作這樣一個Chrome的擴展，我一直想把我購買的台灣BookWalker的漫畫等圖片保存下來自己觀看。但我在使用中遇到了一些問題，可以的話還望您能指點一二。
我使用最新版Chrome（75.0.3770.100）加載此插件后，在使用在綫閲讀書籍功能時，插件的確提示有數個文件可供下載，但是當我打開下載的tar包后，解壓發現裏面的圖片雖然分辨率正確，但是内容全部爲無法辨認的馬賽克，選一張圖片作爲示例：
[https://www.betaarchive.com/imageupload/2019-07/1563198746.or.39637.jpeg](url)

請問是我哪裏的設置有問題，還是有其他原因？我使用的是Windows10系統。

非常感謝！

**Comment by CindyLinz** [comment]
會看到這樣的圖片是正確. 這應該是網站平台為了防止網友隨意抓圖去散佈, 他把一頁畫面切成格子狀, 然後打亂它們的順序. 他的網頁閱讀器裡應該有記錄打亂的位置, 然後再拼貼回來給登入的會員觀看...

我這個 extension 其實就只是用來抓這種被打亂的圖片, 原本是想自己練習寫個會自動拼圖的 AI 程式來玩玩的, 但後半這動作一直沒有時間做 ^^|
